version: "3.9"

services:

  mysql:
    image: mysql:8.0.36
    container_name: eventzen-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventzen_db
    ports:
      - "3307:3306"
    volumes:
      - ./db/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  backend:
    build: ./eventzen
    container_name: eventzen-backend
    depends_on:
       mysql:
         condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eventzen_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect

  frontend:
    build: ./eventzen-frontend
    container_name: eventzen-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8080   # FIXED

volumes:
  mysql-data: